import type {
  Employee,
  Enquiry,
  LeaveRequest,
  Project,
  Task,
  WorkbenchNotification,
  AuditLogEntry,
  ActivityEvent,
} from "./types"

/**
 * ---------------------------------------------------------------------------
 * DEMO / MOCK DATA
 * ---------------------------------------------------------------------------
 * This module is the clearly-marked mock data layer for the Workbench UI.
 * It is NOT real company data. When Neon PostgreSQL is wired in, these seeds
 * are replaced by queries against the tables described in the spec
 * (users, employees, projects, tasks, enquiries, ...). The shapes here match
 * the intended relational schema so swapping the data source is mechanical.
 */

export const PUBLIC_WEBSITE_STATS = {
  totalEnquiries: 347,
  completedProjects: 149,
  liveProjects: 6,
}

export const employees: Employee[] = [
  {
    id: "EMP-001",
    name: "Aarav Mehta",
    email: "aarav@gritgrid.in",
    role: "OWNER",
    department: "Leadership",
    title: "Founder & CEO",
    phone: "+91 90000 10001",
    joinedDate: "2021-02-01",
    skills: ["Strategy", "Architecture", "Cloud"],
    status: "Active",
    attendanceStatus: "Checked In",
    lastActive: "2 min ago",
    avatarColor: "#7c3aed",
  },
  {
    id: "EMP-002",
    name: "Neha Kapoor",
    email: "neha@gritgrid.in",
    role: "MANAGER",
    department: "Engineering",
    title: "Engineering Manager",
    phone: "+91 90000 10002",
    joinedDate: "2021-06-14",
    skills: ["Team Lead", "Next.js", "Systems"],
    status: "Active",
    attendanceStatus: "Checked In",
    lastActive: "5 min ago",
    avatarColor: "#2563eb",
  },
  {
    id: "EMP-003",
    name: "Rohan Verma",
    email: "rohan@gritgrid.in",
    role: "MANAGER",
    department: "Delivery",
    title: "Delivery Manager",
    phone: "+91 90000 10003",
    joinedDate: "2022-01-10",
    skills: ["Client Success", "Planning", "QA"],
    status: "Active",
    attendanceStatus: "Checked Out",
    lastActive: "1 hr ago",
    avatarColor: "#0ea5e9",
  },
  {
    id: "EMP-004",
    name: "Priya Nair",
    email: "priya@gritgrid.in",
    role: "EMPLOYEE",
    department: "Engineering",
    title: "Full-stack Engineer",
    phone: "+91 90000 10004",
    joinedDate: "2022-08-22",
    skills: ["React", "Node", "PostgreSQL"],
    status: "Active",
    attendanceStatus: "Checked In",
    lastActive: "just now",
    avatarColor: "#f97316",
  },
  {
    id: "EMP-005",
    name: "Karan Singh",
    email: "karan@gritgrid.in",
    role: "EMPLOYEE",
    department: "Design",
    title: "Product Designer",
    phone: "+91 90000 10005",
    joinedDate: "2023-03-05",
    skills: ["UI", "Prototyping", "Design Systems"],
    status: "On Leave",
    attendanceStatus: "Not Started",
    lastActive: "yesterday",
    avatarColor: "#10b981",
  },
  {
    id: "EMP-006",
    name: "Ananya Rao",
    email: "ananya@gritgrid.in",
    role: "EMPLOYEE",
    department: "Engineering",
    title: "Backend Engineer",
    phone: "+91 90000 10006",
    joinedDate: "2023-07-18",
    skills: ["Go", "Postgres", "Infra"],
    status: "Active",
    attendanceStatus: "Checked In",
    lastActive: "12 min ago",
    avatarColor: "#e11d48",
  },
  {
    id: "EMP-007",
    name: "Vikram Desai",
    email: "vikram@gritgrid.in",
    role: "EMPLOYEE",
    department: "Sales",
    title: "Business Development",
    phone: "+91 90000 10007",
    joinedDate: "2023-11-02",
    skills: ["Leads", "CRM", "Negotiation"],
    status: "Active",
    attendanceStatus: "Checked In",
    lastActive: "20 min ago",
    avatarColor: "#f59e0b",
  },
]

export const projects: Project[] = [
  {
    id: "PRJ-2401",
    name: "Aurora Retail Platform",
    client: "Aurora Retail Pvt Ltd",
    category: "Web Platform",
    description:
      "Headless commerce platform with real-time inventory sync and a merchandising console.",
    managerId: "EMP-002",
    memberIds: ["EMP-004", "EMP-006", "EMP-005"],
    startDate: "2024-01-15",
    deadline: "2025-11-30",
    progress: 72,
    status: "Active",
    lastActivity: "2 hrs ago",
    value: 4200000,
  },
  {
    id: "PRJ-2402",
    name: "MediTrack Mobile",
    client: "MediTrack Health",
    category: "Mobile App",
    description:
      "Patient adherence app with reminders, secure records and clinician dashboards.",
    managerId: "EMP-003",
    memberIds: ["EMP-004", "EMP-005"],
    startDate: "2024-03-01",
    deadline: "2025-10-10",
    progress: 48,
    status: "Active",
    lastActivity: "yesterday",
    value: 2800000,
  },
  {
    id: "PRJ-2403",
    name: "GridOps Internal Tooling",
    client: "GritGrid Technologies",
    category: "Internal",
    description:
      "Operational tooling and workflow automation for internal delivery teams.",
    managerId: "EMP-002",
    memberIds: ["EMP-006"],
    startDate: "2024-05-20",
    deadline: "2025-12-15",
    progress: 30,
    status: "Planning",
    lastActivity: "3 days ago",
    value: 900000,
  },
  {
    id: "PRJ-2404",
    name: "Finlytics Dashboard",
    client: "Finlytics Capital",
    category: "Data / Analytics",
    description:
      "Portfolio analytics with streaming market data and configurable risk reports.",
    managerId: "EMP-003",
    memberIds: ["EMP-004", "EMP-006"],
    startDate: "2024-02-10",
    deadline: "2025-09-30",
    progress: 88,
    status: "Review",
    lastActivity: "6 hrs ago",
    value: 3600000,
  },
  {
    id: "PRJ-2405",
    name: "Voltway Fleet Portal",
    client: "Voltway Mobility",
    category: "Web Platform",
    description: "EV fleet management portal with telemetry and maintenance scheduling.",
    managerId: "EMP-002",
    memberIds: ["EMP-005", "EMP-007"],
    startDate: "2024-06-01",
    deadline: "2026-01-20",
    progress: 15,
    status: "On Hold",
    lastActivity: "1 week ago",
    value: 2100000,
  },
]

export const tasks: Task[] = [
  {
    id: "TSK-5001",
    title: "Implement inventory sync webhook",
    description: "Consume supplier webhooks and reconcile stock levels in near real-time.",
    projectId: "PRJ-2401",
    assigneeId: "EMP-004",
    priority: "High",
    status: "In Progress",
    dueDate: "2025-09-18",
    createdDate: "2025-09-08",
    updatedDate: "2025-09-13",
  },
  {
    id: "TSK-5002",
    title: "Design merchandising console",
    description: "High-fidelity screens for the merchandising and promotions console.",
    projectId: "PRJ-2401",
    assigneeId: "EMP-005",
    priority: "Medium",
    status: "Review",
    dueDate: "2025-09-16",
    createdDate: "2025-09-05",
    updatedDate: "2025-09-12",
  },
  {
    id: "TSK-5003",
    title: "Set up clinician dashboard auth",
    description: "Role-based access for clinicians with audit logging.",
    projectId: "PRJ-2402",
    assigneeId: "EMP-004",
    priority: "Urgent",
    status: "Todo",
    dueDate: "2025-09-15",
    createdDate: "2025-09-10",
    updatedDate: "2025-09-11",
  },
  {
    id: "TSK-5004",
    title: "Optimize risk report queries",
    description: "Reduce p95 latency on the risk report aggregation queries.",
    projectId: "PRJ-2404",
    assigneeId: "EMP-006",
    priority: "High",
    status: "Blocked",
    dueDate: "2025-09-14",
    createdDate: "2025-09-02",
    updatedDate: "2025-09-13",
  },
  {
    id: "TSK-5005",
    title: "Write E2E tests for checkout",
    description: "Cover the full checkout journey with Playwright.",
    projectId: "PRJ-2401",
    assigneeId: "EMP-006",
    priority: "Medium",
    status: "Todo",
    dueDate: "2025-09-22",
    createdDate: "2025-09-11",
    updatedDate: "2025-09-11",
  },
  {
    id: "TSK-5006",
    title: "Finalize Finlytics UAT sign-off",
    description: "Coordinate UAT feedback and prepare release notes.",
    projectId: "PRJ-2404",
    assigneeId: "EMP-004",
    priority: "High",
    status: "Completed",
    dueDate: "2025-09-10",
    createdDate: "2025-09-01",
    updatedDate: "2025-09-10",
  },
]

export const enquiries: Enquiry[] = [
  {
    id: "ENQ-8001",
    name: "Sanjay Gupta",
    contact: "+91 98111 22334",
    email: "sanjay@brightretail.com",
    source: "Website",
    service: "E-commerce Platform",
    description: "Looking to rebuild our storefront with headless commerce.",
    assigneeId: "EMP-007",
    priority: "High",
    status: "Qualified",
    createdDate: "2025-09-09",
    updatedDate: "2025-09-12",
    followUpDate: "2025-09-16",
  },
  {
    id: "ENQ-8002",
    name: "Meera Iyer",
    contact: "+91 99887 66554",
    email: "meera@clinicplus.in",
    source: "Referral",
    service: "Mobile App",
    description: "Patient scheduling app for a chain of clinics.",
    assigneeId: "EMP-007",
    priority: "Medium",
    status: "Contacted",
    createdDate: "2025-09-11",
    updatedDate: "2025-09-12",
    followUpDate: "2025-09-15",
  },
  {
    id: "ENQ-8003",
    name: "David Fernandes",
    contact: "+91 97654 33210",
    email: "david@logipro.co",
    source: "LinkedIn",
    service: "Logistics Dashboard",
    description: "Real-time fleet tracking and analytics dashboard.",
    assigneeId: null,
    priority: "Urgent",
    status: "New",
    createdDate: "2025-09-13",
    updatedDate: "2025-09-13",
    followUpDate: null,
  },
  {
    id: "ENQ-8004",
    name: "Ritu Malhotra",
    contact: "+91 96543 22110",
    email: "ritu@edulearn.org",
    source: "Website",
    service: "Learning Platform",
    description: "LMS with live classes and assessments.",
    assigneeId: "EMP-007",
    priority: "Low",
    status: "In Progress",
    createdDate: "2025-09-07",
    updatedDate: "2025-09-12",
    followUpDate: "2025-09-18",
  },
]

export const leaveRequests: LeaveRequest[] = [
  {
    id: "LV-3001",
    employeeId: "EMP-005",
    type: "Casual Leave",
    startDate: "2025-09-13",
    endDate: "2025-09-15",
    days: 3,
    reason: "Family function out of town.",
    status: "Approved",
    appliedDate: "2025-09-05",
  },
  {
    id: "LV-3002",
    employeeId: "EMP-004",
    type: "Sick Leave",
    startDate: "2025-09-18",
    endDate: "2025-09-18",
    days: 1,
    reason: "Medical appointment.",
    status: "Pending",
    appliedDate: "2025-09-12",
  },
  {
    id: "LV-3003",
    employeeId: "EMP-006",
    type: "Earned Leave",
    startDate: "2025-09-25",
    endDate: "2025-09-27",
    days: 3,
    reason: "Short vacation.",
    status: "Pending",
    appliedDate: "2025-09-13",
  },
]

export const initialNotifications: WorkbenchNotification[] = [
  {
    id: "NTF-1",
    type: "enquiry",
    title: "New enquiry received",
    body: "David Fernandes submitted an enquiry for a Logistics Dashboard.",
    timestamp: "2025-09-13T09:20:00",
    read: false,
    forRoles: ["OWNER", "MANAGER", "EMPLOYEE"],
  },
  {
    id: "NTF-2",
    type: "task",
    title: "Task assigned",
    body: "You were assigned TSK-5003 — Set up clinician dashboard auth.",
    timestamp: "2025-09-13T08:50:00",
    read: false,
    forUserId: "EMP-004",
  },
  {
    id: "NTF-3",
    type: "deadline",
    title: "Deadline approaching",
    body: "TSK-5004 is due tomorrow and currently Blocked.",
    timestamp: "2025-09-12T16:30:00",
    read: true,
    forRoles: ["OWNER", "MANAGER"],
  },
  {
    id: "NTF-4",
    type: "leave",
    title: "Leave approved",
    body: "Your casual leave for 13–15 Sep was approved.",
    timestamp: "2025-09-11T11:00:00",
    read: true,
    forUserId: "EMP-005",
  },
]

export const initialAuditLog: AuditLogEntry[] = [
  {
    id: "AUD-1",
    actorId: "EMP-002",
    actorName: "Neha Kapoor",
    action: "project.status_changed",
    entity: "Project",
    entityId: "PRJ-2404",
    timestamp: "2025-09-13T07:40:00",
    metadata: { from: "Active", to: "Review" },
  },
  {
    id: "AUD-2",
    actorId: "EMP-007",
    actorName: "Vikram Desai",
    action: "enquiry.created",
    entity: "Enquiry",
    entityId: "ENQ-8003",
    timestamp: "2025-09-13T09:20:00",
  },
  {
    id: "AUD-3",
    actorId: "EMP-001",
    actorName: "Aarav Mehta",
    action: "auth.login",
    entity: "Session",
    entityId: "EMP-001",
    timestamp: "2025-09-13T08:05:00",
  },
]

export const todayActivity: ActivityEvent[] = [
  { id: "ACT-1", time: "09:10", label: "Checked in", kind: "check-in" },
  { id: "ACT-2", time: "09:35", label: "Started TSK-5001 — inventory sync", kind: "task" },
  { id: "ACT-3", time: "11:20", label: "Client enquiry received (ENQ-8003)", kind: "enquiry" },
  { id: "ACT-4", time: "13:40", label: "Finlytics milestone updated to Review", kind: "project" },
  { id: "ACT-5", time: "15:05", label: "Statistics update requested", kind: "approval" },
]

export const financeSummary = {
  revenue: 18600000,
  expenses: 9400000,
  pendingPayments: 3200000,
  completedPayments: 15400000,
  projectValue: projects.reduce((sum, p) => sum + p.value, 0),
  monthly: [
    { month: "Apr", revenue: 2400000, expenses: 1300000 },
    { month: "May", revenue: 2650000, expenses: 1500000 },
    { month: "Jun", revenue: 2900000, expenses: 1450000 },
    { month: "Jul", revenue: 3100000, expenses: 1700000 },
    { month: "Aug", revenue: 3350000, expenses: 1650000 },
    { month: "Sep", revenue: 4200000, expenses: 1800000 },
  ],
}

export const documents = [
  { id: "DOC-1", name: "Employee Handbook 2025", category: "HR", size: "2.4 MB", updated: "2025-08-30", restricted: false },
  { id: "DOC-2", name: "Leave & Attendance Policy", category: "Policies", size: "820 KB", updated: "2025-07-12", restricted: false },
  { id: "DOC-3", name: "Aurora Retail — SOW", category: "Project Documents", size: "1.1 MB", updated: "2025-09-01", restricted: true },
  { id: "DOC-4", name: "Q3 Financial Report", category: "Reports", size: "3.6 MB", updated: "2025-09-05", restricted: true },
  { id: "DOC-5", name: "Project Kickoff Template", category: "Templates", size: "540 KB", updated: "2025-06-20", restricted: false },
  { id: "DOC-6", name: "Company Profile Deck", category: "Company Documents", size: "5.2 MB", updated: "2025-05-15", restricted: false },
]

export const DOCUMENT_CATEGORIES = [
  "Company Documents",
  "HR",
  "Policies",
  "Project Documents",
  "Templates",
  "Reports",
] as const

export function getEmployee(id: string | null | undefined) {
  return employees.find((e) => e.id === id)
}

export function initials(name: string) {
  return name
    .split(" ")
    .map((p) => p[0])
    .slice(0, 2)
    .join("")
    .toUpperCase()
}
